POST http://localhost:4000/token_refresh
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Cookie: ogedahsned=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoidG9tZm9yZCIsImlhdCI6MTYyNTMzNDAxNiwiZXhwIjoxNjI1OTM4ODE2fQ.DNPNNgSgFZJX-pfNPRSCgYHaW7wTeHWUhG8euLi6zSE
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Accept: */*
Cache-Control: no-cache
Content-Length: 0
